/*
 * refresh-tickets.js
 * ------------------
 * Regenerates the "Connected Linear tickets" table(s) in the Q3 strategy pages
 * from their Linear projects. Currently covers TWO pages:
 *   - proactive-messaging-prd.html  ← Linear project "proactive chat"
 *   - nl-commands.html              ← Linear project "natural language"
 *
 * HOW IT WORKS (the four steps, per page):
 *   1. AUTH   — read your Linear API key from the LINEAR_API_KEY environment variable
 *   2. QUERY  — ask Linear's GraphQL API for the project's issues
 *   3. BUILD  — turn those issues into HTML table rows
 *   4. REWRITE— swap the HTML between the <!-- TICKETS:START --> and <!-- TICKETS:END --> markers
 *
 * RUN IT:
 *   export LINEAR_API_KEY=lin_api_xxxxx      # your personal Linear API key
 *   node refresh-tickets.js
 *
 * Node 18+ has a built-in `fetch`, so there are no dependencies to install.
 *
 * TO ADD ANOTHER PAGE LATER: add an entry to the TARGETS array below.
 */

const fs = require('fs');
const path = require('path');

// ---- config: one entry per page we keep in sync -------------------------
const TARGETS = [
  {
    project: 'proactive chat',
    file: 'proactive-messaging-prd.html',
    // The intro sentence shown above the table (the link is part of it):
    intro: 'Live work for this PRD is tracked in the <a class="inline" href="https://linear.app/hatchbaby/project/proactive-chat-b50894f7c7c3" target="_blank" rel="noopener">"proactive chat" Linear project</a>.',
  },
  {
    project: 'natural language',
    file: 'nl-commands.html',
    intro: 'Tracked in the <a class="inline" href="https://linear.app/hatchbaby/project/natural-language-a74075a90402" target="_blank" rel="noopener">"natural language" Linear project</a>.',
  },
];

const START = '<!-- TICKETS:START — auto-generated by refresh-tickets.js; do not hand-edit between these markers -->';
const END = '<!-- TICKETS:END -->';

// ---- 1. AUTH ------------------------------------------------------------
// Linear personal API keys go straight in the Authorization header (no "Bearer ").
// We read it from the environment so the secret never lives in this file or the pages.
const API_KEY = process.env.LINEAR_API_KEY;
if (!API_KEY) {
  console.error('❌ Missing LINEAR_API_KEY. Run:  export LINEAR_API_KEY=lin_api_xxx');
  process.exit(1);
}

// ---- small helpers ------------------------------------------------------
function esc(s) {
  return String(s || '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function badgeClass(stateName) {
  const n = (stateName || '').toLowerCase();
  if (n.includes('progress')) return 'badge-progress';
  if (n.includes('review')) return 'badge-review';
  if (n.includes('done') || n.includes('complete')) return 'badge-done';
  return 'badge-todo'; // Todo, Backlog, Triage, Canceled, anything else
}

function today() {
  return new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

// ---- 2. QUERY -----------------------------------------------------------
const query = `
  query ($name: String!) {
    projects(filter: { name: { eq: $name } }, first: 1) {
      nodes {
        name
        issues(first: 100) {
          nodes {
            identifier
            title
            url
            state { name }
            assignee { name }
          }
        }
      }
    }
  }`;

async function fetchIssues(projectName) {
  const res = await fetch('https://api.linear.app/graphql', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': API_KEY },
    body: JSON.stringify({ query, variables: { name: projectName } }),
  });
  if (!res.ok) throw new Error(`Linear API returned HTTP ${res.status} (check your API key)`);
  const json = await res.json();
  if (json.errors) throw new Error('Linear GraphQL error: ' + JSON.stringify(json.errors));
  const project = json.data.projects.nodes[0];
  if (!project) throw new Error(`No Linear project named "${projectName}" found`);

  // Sort by issue number (SLE-27 before SLE-466) for a stable order.
  return project.issues.nodes.slice().sort((a, b) => {
    return parseInt(a.identifier.split('-')[1], 10) - parseInt(b.identifier.split('-')[1], 10);
  });
}

// ---- 3 + 4. BUILD + REWRITE (per page) ----------------------------------
async function refreshTarget(target) {
  const issues = await fetchIssues(target.project);

  const rows = issues.map((i) => {
    const owner = i.assignee ? esc(i.assignee.name.split(' ')[0]) : '—';
    const status = i.state ? i.state.name : 'Unknown';
    return `          <tr>
            <td><a class="inline" href="${i.url}" target="_blank" rel="noopener">${esc(i.identifier)}</a></td>
            <td>${esc(i.title)}</td>
            <td><span class="badge ${badgeClass(status)}">${esc(status)}</span></td>
            <td>${owner}</td>
          </tr>`;
  }).join('\n');

  const tableBody = issues.length
    ? rows
    : `          <tr><td colspan="4">No tickets in the project yet.</td></tr>`;

  const block = `${START}
      <p class="section-desc">${target.intro} Snapshot as of ${today()} — open the project for the current state.</p>
      <table>
        <thead><tr><th>Ticket</th><th>Title</th><th>Status</th><th>Owner</th></tr></thead>
        <tbody>
${tableBody}
        </tbody>
      </table>
      ${END}`;

  const file = path.join(__dirname, target.file);
  const html = fs.readFileSync(file, 'utf8');
  const s = html.indexOf(START);
  const e = html.indexOf(END);
  if (s === -1 || e === -1) throw new Error(`Could not find TICKETS markers in ${target.file}`);

  fs.writeFileSync(file, html.slice(0, s) + block + html.slice(e + END.length));
  console.log(`✅ ${target.file}: ${issues.length} ticket(s) from "${target.project}"`);
}

// ---- run every target ---------------------------------------------------
async function main() {
  for (const target of TARGETS) {
    try {
      await refreshTarget(target);
    } catch (err) {
      console.error(`❌ ${target.file}: ${err.message}`);
    }
  }
  console.log(`\nDone (as of ${today()}). Redeploy the site (and hard-refresh the preview) to see changes.`);
}

main().catch((err) => {
  console.error('❌ Unexpected error:', err.message);
  process.exit(1);
});
